### PR TITLE
Implement Playback Speed

### PR DESCRIPTION
**Pull request by quangquy87**
How to implement playbackRate?
please!

### CODE REVIEW

**Comment by boyan01** [comment]
Can I ask what is the intention of this PR？

**Comment by quangquy87** [comment]
> Can I ask what is the intention of this PR？

I want to change audio playback speed to 0.5, 0.75, 1, 2. please tell me how to get this.
Best regards!

**Comment by boyan01** [comment]
https://stackoverflow.com/questions/31947460/changing-playback-speed-in-exoplayer

**Comment by quangquy87** [comment]
> https://stackoverflow.com/questions/31947460/changing-playback-speed-in-exoplayer

Thanks for taking the time for me.
I want to setSpeed from flutter, how do I do it?
Sorry if I make you feel uncomfortable!

**Comment by boyan01** [comment]
https://github.com/boyan01/flutter-music-player project is not implement `setSpeed` yet.

If you want implement this feature, you can add function named `setSpeed` in flutter side, then use MethodChannel to realize the function of setting the playback speed on the Android / iOS side.

**Pull request closed without merging**
